package com.keyflux

import java.util.Locale

object Localization {
    internal val translations = mapOf(
        "ar" to mapOf(
            "keyflux_category_title" to "إعدادات KeyFlux",
            "keyflux_enable_ai_title" to "ميزات الكتابة الذكية",
            "keyflux_enable_ai_summary" to "تفعيل الكتابة الذكية والاقتراحات التلقائية",
            "keyflux_enable_grammar_title" to "التدقيق اللغوي",
            "keyflux_enable_grammar_summary" to "تحديد وتصحيح الأخطاء اللغوية والإملائية",
            "keyflux_enable_multilingual_title" to "الكتابة متعددة اللغات",
            "keyflux_enable_multilingual_summary" to "الكتابة بلغات متعددة تلقائياً في نفس الوقت",
            "keyflux_enable_floating_title" to "تخطيط الكيبورد العائم",
            "keyflux_enable_floating_summary" to "تفعيل وضع الكيبورد العائم تلقائياً في الوضع الأفقي أو النوافذ المتعددة",
            "keyflux_enable_emoji_kitchen_title" to "مطبخ الإيموجي",
            "keyflux_enable_emoji_kitchen_summary" to "تصفح ودمج ملصقات الإيموجي للحصول على ملصقات جديدة",
            "keyflux_enable_access_point_title" to "إعادة تصميم قائمة الميزات",
            "keyflux_enable_access_point_summary" to "تفعيل المظهر الحريري، خط النظام، والسمات المخصصة",
            "keyflux_enable_amoled_title" to "مظهر AMOLED الأسود",
            "keyflux_enable_amoled_summary" to "تفعيل الخلفية السوداء الداكنة بالكامل لتوفير الطاقة",
            "keyflux_metered_downloads_title" to "التنزيل عبر شبكة الهاتف",
            "keyflux_metered_downloads_summary" to "السماح بتنزيل حزم اللغات والصوت عبر بيانات الهاتف",
            "keyflux_force_incognito_title" to "التصفح المتخفي الإجباري",
            "keyflux_force_incognito_summary" to "إجبار الكيبورد على وضع التصفح المتخفي لمنع حفظ ما تكتبه",
            "keyflux_enable_privacy_title" to "حظر التتبع والتحليلات",
            "keyflux_enable_privacy_summary" to "تعطيل إرسال إحصائيات الكتابة والسرعة والتدريب المحلي لـ Google",
            "keyflux_secure_clipboard_title" to "حماية نصوص الحافظة",
            "keyflux_secure_clipboard_summary" to "منع حفظ كلمات المرور ورموز التحقق (OTP) في سجل الحافظة",
            "keyflux_clip_size_title" to "عدد نصوص الحافظة",
            "keyflux_clip_size_summary" to "الحالي: %s",
            "keyflux_clip_days_title" to "مدة الاحتفاظ بنصوص الحافظة",
            "keyflux_clip_days_summary" to "أيام الاحتفاظ بنصوص الحافظة. أدخل 0 للابد (الحالي: %s)",
            "keyflux_log_switch_title" to "تسجيل السجلات",
            "keyflux_log_switch_summary" to "كتابة سجلات التصحيح إلى Xposed",
            "keyflux_force_stop_title" to "تطبيق التغييرات (إيقاف إجباري)",
            "keyflux_force_stop_summary" to "إعادة تشغيل الكيبورد لتطبيق الإعدادات الجديدة",
            "forever" to "للأبد",
            "days" to "أيام",
            "keyflux_settings_header_experimental_title" to "الميزات التجريبية والذكاء الاصطناعي",
            "keyflux_enable_inline_suggestions_title" to "اقتراحات النصوص الذكية المدمجة",
            "keyflux_enable_inline_suggestions_summary" to "اقتراح جمل كاملة أو كلمات متعددة وتكملتها بسحبة واحدة",
            "keyflux_enable_proactive_emoji_title" to "مطبخ الإيموجي الاستباقي",
            "keyflux_enable_proactive_emoji_summary" to "اقتراحات تفاعلية ومتحركة لدمج الإيموجيات أثناء الكتابة",
            "keyflux_enable_clipboard_chips_title" to "أزرار الحافظة السريعة",
            "keyflux_enable_clipboard_chips_summary" to "إظهار أزرار ذكية ولصق سريع واستخراج بيانات عند نسخ أي نص",
            "keyflux_enable_tflite_engine_title" to "محرك الذكاء الاصطناعي TFLite",
            "keyflux_enable_tflite_engine_summary" to "تشغيل محرك الشبكات العصبية محلياً لتوقع كلمات وإيموجي بدقة فائقة",
            "keyflux_enable_fast_access_title" to "شريط الوصول السريع الجديد",
            "keyflux_enable_fast_access_summary" to "تفعيل شريط الوصول السريع وخيارات التصميم الحديثة (Google Sans)",
            "keyflux_warning_failed_hooks_title" to "تنبيه التوافقية: تم تعطيل بعض الميزات",
            "keyflux_warning_failed_hooks_summary" to "فشلت الهوكات التالية: %s. قد لا يتوافق إصدار Gboard هذا. يرجى تحديث الإضافة.",
            "keyflux_feature_unavailable_clipboard" to "غير متوفرة بسبب عدم توافق دالّة الحافظة.",
            "keyflux_feature_unavailable_flags" to "غير متوفرة بسبب عدم توافق دالّة النظام.",
            "keyflux_feature_unavailable_theme" to "غير متوفرة بسبب عدم توافق دالّة المظهر."
        ),
        "fa" to mapOf(
            "category_title" to "تنظیمات KeyFlux",
            "enable_ai_title" to "ویژگی‌های تایپ هوشمند",
            "enable_ai_summary" to "فعال‌سازی تکمیل خودکار هوشمند و پیشنهادات خطی",
            "enable_grammar_title" to "بررسی دستور زبان",
            "enable_grammar_summary" to "برجسته‌سازی و اصلاح خطاهای دستوری",
            "enable_multilingual_title" to "تایپ چندزبانه",
            "enable_multilingual_summary" to "تایپ همزمان به چندین زبان",
            "enable_floating_title" to "طرح‌بندی صفحه‌کلید شناور",
            "enable_floating_summary" to "شناور شدن خودکار صفحه‌کلید در حالت افقی یا چندپنجره‌ای",
            "enable_emoji_kitchen_title" to "آشپزخانه ایموجی",
            "enable_emoji_kitchen_summary" to "مرور و ترکیب استیکرها و ایموجی‌ها",
            "enable_access_point_title" to "طراحی مجدد منوی دسترسی سریع",
            "enable_access_point_summary" to "تم ابریشمی، فونت سیستم، تم‌های سفارشی",
            "enable_amoled_title" to "تم مشکی AMOLED",
            "enable_amoled_summary" to "خلف‌زمینه مشکی خالص",
            "metered_downloads_title" to "دانلود با اینترنت محدود",
            "metered_downloads_summary" to "اجازه دانلود بسته‌های زبان و گفتار با داده تلفن همراه",
            "force_incognito_title" to "اجبار حالت ناشناس",
            "force_incognito_summary" to "اجبار صفحه‌کلید به حالت ناشناس برای جلوگیری از ذخیره تاریخچه تایپ",
            "enable_privacy_title" to "مسدود کردن تله‌متری و آنالیزها",
            "enable_privacy_summary" to "غیرفعال‌سازی آمار تایپ، گزارش‌های سرعت و به‌روزرسانی‌های یادگیری محلی",
            "secure_clipboard_title" to "محافظت از حافظه موقت",
            "secure_clipboard_summary" to "جلوگیری از ذخیره رمزهای عبور و رمزهای یک‌بار مصرف (OTP) در تاریخچه حافظه موقت",
            "clip_size_title" to "اندازه تاریخچه حافظه موقت",
            "clip_size_summary" to "فعلی: %s",
            "clip_days_title" to "زمان انقضای حافظه موقت",
            "clip_days_summary" to "تعداد روزهای نگهداری. برای همیشه 0 را وارد کنید (فعلی: %s)",
            "log_switch_title" to "ثبت گزارش‌ها",
            "log_switch_summary" to "نوشتن گزارش‌های عیب‌یابی در Xposed",
            "force_stop_title" to "اعمال تغییرات (توقف اجباری)",
            "force_stop_summary" to "راه‌اندازی مجدد صفحه‌کلید برای اعمال تنظیمات",
            "forever" to "برای همیشه",
            "days" to "روز"
        ),
        "ur" to mapOf(
            "category_title" to "کی فلکس ترتیبات",
            "enable_ai_title" to "سمارٹ ٹائپنگ کی خصوصیات",
            "enable_ai_summary" to "سمارٹ کمپوز اور ان لائن تجاویز فعال کریں",
            "enable_grammar_title" to "گرامر کی جانچ",
            "enable_grammar_summary" to "گرامر کی غلطیوں کو نشان زد اور درست کریں",
            "enable_multilingual_title" to "کثیر لسانی ٹائپنگ",
            "enable_multilingual_summary" to "ایک ہی وقت میں متعدد زبانوں میں ٹائپ کریں",
            "enable_floating_title" to "فلوٹنگ کی بورڈ لے آؤٹ",
            "enable_floating_summary" to "لینڈ اسکیپ یا ملٹی ونڈو موڈ میں خودکار فلوٹنگ کی بورڈ",
            "enable_emoji_kitchen_title" to "ایموجی کچن",
            "enable_emoji_kitchen_summary" to "اسٹیکرز اور ایموجیز کو براؤز اور یکجا کریں",
            "enable_access_point_title" to "رسائی پوائنٹ مینو کی دوبارہ ترتیب",
            "enable_access_point_summary" to "سلک تھیم، سسٹم فونٹ، اور اپنی مرضی کے تھیمز",
            "enable_amoled_title" to "AMOLED بلیک تھیم",
            "enable_amoled_summary" to "خالص سیاہ پس منظر والی تھیم",
            "metered_downloads_title" to "محدود نیٹ ورک ڈاؤن لوڈز",
            "metered_downloads_summary" to "موبائل ڈیٹا پر زبان اور اسپیچ پیک ڈاؤن لوڈ کی اجازت دیں",
            "force_incognito_title" to "لازمی انکوگنیٹو موڈ",
            "force_incognito_summary" to "ٹائپنگ ہسٹری کو محفوظ ہونے سے روکنے کے لیے کی بورڈ کو انکوگنیٹو موڈ پر مجبور کریں",
            "enable_privacy_title" to "ٹیلی میٹری اور تجزیات بلاک کریں",
            "enable_privacy_summary" to "ٹائپنگ کے اعداد و شمار اور گوگل کو رپورٹ بھیجنا غیر فعال کریں",
            "secure_clipboard_title" to "کلپ بورڈ تحفظ",
            "secure_clipboard_summary" to "کلپ بورڈ ہسٹری میں پاس ورڈز اور یک وقتی پاس ورڈ (OTP) کو محفوظ ہونے سے روکیں",
            "clip_size_title" to "کلپ بورڈ ہسٹری کا سائز",
            "clip_size_summary" to "موجودہ: %s",
            "clip_days_title" to "کلپ بورڈ کی میعاد",
            "clip_days_summary" to "کلپ بورڈ آئٹمز رکھنے کے دن۔ ہمیشہ کے لیے 0 درج کریں (موجودہ: %s)",
            "log_switch_title" to "لاگ سوئچ",
            "log_switch_summary" to "Xposed پر ڈیبگ لاگز لکھیں",
            "force_stop_title" to "تبدیلیاں لاگو کریں (زبردستی روکیں)",
            "force_stop_summary" to "ترتیبات لاگو کرنے کے لیے کی بورڈ کو دوبارہ شروع کریں",
            "forever" to "ہمیشہ کے لیے",
            "days" to "دن"
        ),
        "es" to mapOf(
            "category_title" to "Ajustes de KeyFlux",
            "enable_ai_title" to "Funciones de escritura inteligente",
            "enable_ai_summary" to "Activar redacción inteligente y sugerencias integradas",
            "enable_grammar_title" to "Corrector gramatical",
            "enable_grammar_summary" to "Resaltar y corregir errores gramaticales",
            "enable_multilingual_title" to "Escritura multilingüe",
            "enable_multilingual_summary" to "Escribir en varios idiomas simultáneamente",
            "enable_floating_title" to "Teclado flotante",
            "enable_floating_summary" to "Teclado flotante automático en modo horizontal o multipantalla",
            "enable_emoji_kitchen_title" to "Cocina de Emojis",
            "enable_emoji_kitchen_summary" to "Explorar y combinar pegatinas y emojis",
            "enable_access_point_title" to "Rediseñar menú de puntos de acceso",
            "enable_access_point_summary" to "Tema de seda, fuente del sistema, temas personalizados",
            "enable_amoled_title" to "Tema negro AMOLED",
            "enable_amoled_summary" to "Fondo negro puro",
            "metered_downloads_title" to "Descargas en redes medidas",
            "metered_downloads_summary" to "Permitir descargas de paquetes de idiomas y voz mediante datos móviles",
            "force_incognito_title" to "Forzar modo incógnito",
            "force_incognito_summary" to "Forzar a Gboard en modo incógnito para evitar guardar el historial de escritura",
            "enable_privacy_title" to "Bloquear telemetría y análisis",
            "enable_privacy_summary" to "Desactivar estadísticas de escritura, registros de velocidad y entrenamiento local",
            "secure_clipboard_title" to "Protección del portapapeles",
            "secure_clipboard_summary" to "Evitar guardar contraseñas y códigos de verificación (OTP) en el historial",
            "clip_size_title" to "Tamaño del historial",
            "clip_size_summary" to "Actual: %s",
            "clip_days_title" to "Expiración del portapapeles",
            "clip_days_summary" to "Días para guardar los elementos. Escribe 0 para siempre (Actual: %s)",
            "log_switch_title" to "Registro de depuración",
            "log_switch_summary" to "Escribir registros de depuración en Xposed",
            "force_stop_title" to "Aplicar cambios (Forzar detención)",
            "force_stop_summary" to "Reiniciar el teclado para aplicar la configuración",
            "forever" to "Para siempre",
            "days" to "días"
        ),
        "fr" to mapOf(
            "category_title" to "Paramètres KeyFlux",
            "enable_ai_title" to "Saisie intelligente",
            "enable_ai_summary" to "Activer la rédaction intelligente et les suggestions en ligne",
            "enable_grammar_title" to "Correcteur grammatical",
            "enable_grammar_summary" to "Surligner et corriger les erreurs de grammaire",
            "enable_multilingual_title" to "Saisie multilingue",
            "enable_multilingual_summary" to "Saisir dans plusieurs langues simultanément",
            "enable_floating_title" to "Clavier flottant",
            "enable_floating_summary" to "Clavier flottant automatique en mode paysage ou multi-fenêtres",
            "enable_emoji_kitchen_title" to "Emoji Kitchen",
            "enable_emoji_kitchen_summary" to "Parcourir et combiner des autocollants et des emojis",
            "enable_access_point_title" to "Redessiner le menu",
            "enable_access_point_summary" to "Thème en soie, police système, thèmes personnalisés",
            "enable_amoled_title" to "Thème noir AMOLED",
            "enable_amoled_summary" to "Arrière-plan noir pur",
            "metered_downloads_title" to "Téléchargements limités",
            "metered_downloads_summary" to "Autoriser le téléchargement sur données mobiles",
            "force_incognito_title" to "Forcer le mode navigation privée",
            "force_incognito_summary" to "Forcer Gboard en navigation privée pour éviter d'enregistrer l'historique",
            "enable_privacy_title" to "Bloquer la télémétrie et analyses",
            "enable_privacy_summary" to "Désactiver les statistiques de saisie, les rapports de vitesse et l'apprentissage local",
            "secure_clipboard_title" to "Protection du presse-papiers",
            "secure_clipboard_summary" to "Empêcher l'enregistrement des mots de passe et codes de vérification (OTP) dans l'historique",
            "clip_size_title" to "Taille de l'historique",
            "clip_size_summary" to "Actuel : %s",
            "clip_days_title" to "Expiration du presse-papiers",
            "clip_days_summary" to "Jours de conservation. Entrez 0 pour toujours (Actuel : %s)",
            "log_switch_title" to "Journaux de débogage",
            "log_switch_summary" to "Écrire les journaux de débogage dans Xposed",
            "force_stop_title" to "Appliquer (Forcer l'arrêt)",
            "force_stop_summary" to "Redémarrer le clavier pour appliquer les paramètres",
            "forever" to "Pour toujours",
            "days" to "jours"
        ),
        "de" to mapOf(
            "category_title" to "KeyFlux-Einstellungen",
            "enable_ai_title" to "Intelligentes Tippen",
            "enable_ai_summary" to "Intelligente Texterstellung und Inline-Vorschläge aktivieren",
            "enable_grammar_title" to "Grammatikprüfung",
            "enable_grammar_summary" to "Grammatikfehler hervorheben und korrigieren",
            "enable_multilingual_title" to "Mehrsprachiges Tippen",
            "enable_multilingual_summary" to "Gleichzeitig in mehreren Sprachen tippen",
            "enable_floating_title" to "Schwebende Tastatur",
            "enable_floating_summary" to "Tastatur automatisch schweben lassen",
            "enable_emoji_kitchen_title" to "Emoji-Küche",
            "enable_emoji_kitchen_summary" to "Sticker und Emojis kombinieren",
            "enable_access_point_title" to "Schnellzugriffsmenü ändern",
            "enable_access_point_summary" to "Seiden-Design, Systemschriftart, benutzerdefinierte Designs",
            "enable_amoled_title" to "AMOLED-Schwarz-Design",
            "enable_amoled_summary" to "Tiefschwarzer Hintergrund",
            "metered_downloads_title" to "Getaktete Downloads",
            "metered_downloads_summary" to "Sprachpaket-Downloads über mobile Daten erlauben",
            "force_incognito_title" to "Inkognito-Modus erzwingen",
            "force_incognito_summary" to "Gboard im Inkognito-Modus betreiben, um den Tippverlauf nicht zu speichern",
            "enable_privacy_title" to "Telemetrie & Analyse blockieren",
            "enable_privacy_summary" to "Tippstatistiken, Geschwindigkeitsberichte und lokales Training deaktivieren",
            "secure_clipboard_title" to "Zwischenablage-Schutz",
            "secure_clipboard_summary" to "Speichern von Passwörtern und Einmalpasswörtern (OTP) im Verlauf verhindern",
            "clip_size_title" to "Zwischenablage-Größe",
            "clip_size_summary" to "Aktuell: %s",
            "clip_days_title" to "Ablaufzeit",
            "clip_days_summary" to "Tage zur Aufbewahrung. 0 eingeben für immer (Aktuell: %s)",
            "log_switch_title" to "Debug-Protokolle",
            "log_switch_summary" to "Debug-Protokolle in Xposed schreiben",
            "force_stop_title" to "Übernehmen (Stopp erzwingen)",
            "force_stop_summary" to "Tastatur neu starten, um die Einstellungen zu übernehmen",
            "forever" to "Für immer",
            "days" to "Tage"
        ),
        "ru" to mapOf(
            "category_title" to "Настройки KeyFlux",
            "enable_ai_title" to "Умный ввод",
            "enable_ai_summary" to "Включить автозаполнение и встроенные подсказки",
            "enable_grammar_title" to "Проверка грамматики",
            "enable_grammar_summary" to "Выделение и исправление грамматических ошибок",
            "enable_multilingual_title" to "Многоязычный ввод",
            "enable_multilingual_summary" to "Ввод на нескольких языках одновременно",
            "enable_floating_title" to "Плавающая клавиатура",
            "enable_floating_summary" to "Плавающий режим в ландшафтном или многооконном режиме",
            "enable_emoji_kitchen_title" to "Кухня эмодзи",
            "enable_emoji_kitchen_summary" to "Просмотр и комбинирование стикеров и эмодзи",
            "enable_access_point_title" to "Новое меню быстрого доступа",
            "enable_access_point_summary" to "Шёлковая тема, системный шрифт, пользовательские темы",
            "enable_amoled_title" to "Тёмная тема AMOLED",
            "enable_amoled_summary" to "Чисто черный фон",
            "metered_downloads_title" to "Мобильные загрузки",
            "metered_downloads_summary" to "Разрешить загрузку языковых пакетов через мобильную сеть",
            "force_incognito_title" to "Принудительный режим инкогнито",
            "force_incognito_summary" to "Принудительно запускать Gboard в режиме инкогнито, чтобы не сохранять историю ввода",
            "enable_privacy_title" to "Блокировка телеметрии и аналитики",
            "enable_privacy_summary" to "Отключить статистику ввода, отчеты о скорости и локальное обучение",
            "secure_clipboard_title" to "Защита буфера обмена",
            "secure_clipboard_summary" to "Запретить сохранение паролей и одноразовых кодов (OTP) в истории буфера",
            "clip_size_title" to "Размер буфера обмена",
            "clip_size_summary" to "Текущий размер: %s",
            "clip_days_title" to "Время хранения",
            "clip_days_summary" to "Срок хранения в днях. Введите 0 для вечного хранения (Текущее: %s)",
            "log_switch_title" to "Журнал отладки",
            "log_switch_summary" to "Записывать отчеты об ошибках в Xposed",
            "force_stop_title" to "Применить (Принудительно)",
            "force_stop_summary" to "Перезапустите клавиатуру для применения настроек",
            "forever" to "Навсегда",
            "days" to "дн."
        ),
        "tr" to mapOf(
            "category_title" to "KeyFlux Ayarları",
            "enable_ai_title" to "Akıllı Yazma Özellikleri",
            "enable_ai_summary" to "Akıllı Yazma ve satır içi önerileri etkinleştir",
            "enable_grammar_title" to "Dilbilgisi Denetleyicisi",
            "enable_grammar_summary" to "Dilbilgisi hatalarını vurgula ve düzelt",
            "enable_multilingual_title" to "Çok Dilli Yazma",
            "enable_multilingual_summary" to "Aynı anda birden fazla dilde yazın",
            "enable_floating_title" to "Yüzen Klavye Düzeni",
            "enable_floating_summary" to "Yatay veya çoklu pencere modunda klavyeyi otomatik yüzdür",
            "enable_emoji_kitchen_title" to "Emoji Mutfağı",
            "enable_emoji_kitchen_summary" to "Çıkartmaları ve emojileri gözden geçir ve birleştir",
            "enable_access_point_title" to "Erişim Noktası Menüsünü Yeniden Tasarla",
            "enable_access_point_summary" to "İpek teması, sistem yazı tipi, özel temalar",
            "enable_amoled_title" to "AMOLED Siyah Teması",
            "enable_amoled_summary" to "Saf siyah arka plan teması",
            "metered_downloads_title" to "Tarifeli Ağ İndirmeleri",
            "metered_downloads_summary" to "Mobil veri üzerinden indirmelere izin ver",
            "force_incognito_title" to "Gizli Modu Zorla",
            "force_incognito_summary" to "Yazma geçmişini kaydetmemek için Gboard'u gizli modda çalışmaya zorla",
            "enable_privacy_title" to "Telemetri ve Analizleri Engelle",
            "enable_privacy_summary" to "Yazma istatistiklerini, hız günlüklerini ve yerel eğitimi devre dışı bırak",
            "secure_clipboard_title" to "Pano Koruması",
            "secure_clipboard_summary" to "Şifrelerin ve tek kullanımlık şifrelerin (OTP) panoda saklanmasını engelle",
            "clip_size_title" to "Pano Geçmişi Boyutu",
            "clip_size_summary" to "Mevcut: %s",
            "clip_days_title" to "Pano Geçmişi Süresi",
            "clip_days_summary" to "Pano öğelerini saklama gün sayısı. Sonsuz için 0 girin (Mevcut: %s)",
            "log_switch_title" to "Hata Günlüğü Anahtarı",
            "log_switch_summary" to "Hata ayıklama günlüklerini Xposed'a yaz",
            "force_stop_title" to "Değişiklikleri Uygula (Zorla Durdur)",
            "force_stop_summary" to "Ayarları uygulamak için klavyeyi yeniden başlatın",
            "forever" to "Sonsuza kadar",
            "days" to "gün"
        ),
        "zh" to mapOf(
            "keyflux_log_level_title" to "日志等级",
            "keyflux_log_level_summary" to "记录 %s 及以上等级的模块日志",
            "keyflux_log_level_debug" to "调试",
            "keyflux_log_level_info" to "信息",
            "keyflux_log_level_warn" to "警告",
            "keyflux_log_level_error" to "错误",
            "keyflux_category_title" to "KeyFlux 设置",
            "keyflux_enable_ai_title" to "智能输入功能",
            "keyflux_enable_ai_summary" to "启用智能撰写和内联建议等实验功能",
            "keyflux_enable_grammar_title" to "语法检查",
            "keyflux_enable_grammar_summary" to "检测并修正语法和拼写错误",
            "keyflux_enable_chinese_learning_title" to "增强中文个性化学习",
            "keyflux_enable_chinese_learning_summary" to "在设备本地记录中文输入训练数据并保留用户词频",
            "keyflux_enable_multilingual_title" to "多语言输入",
            "keyflux_enable_multilingual_summary" to "同时使用多种语言输入",
            "keyflux_enable_floating_title" to "自动悬浮键盘",
            "keyflux_enable_floating_summary" to "在横屏或多窗口中自动切换为悬浮布局",
            "keyflux_enable_emoji_kitchen_title" to "表情工坊",
            "keyflux_enable_emoji_kitchen_summary" to "浏览并组合表情和贴纸",
            "keyflux_enable_access_point_title" to "新版功能入口",
            "keyflux_enable_access_point_summary" to "启用新版工具栏、字体和主题入口",
            "keyflux_enable_amoled_title" to "AMOLED 黑色主题",
            "keyflux_enable_amoled_summary" to "在深色模式中使用纯黑背景",
            "keyflux_theme_category_title" to "自定义主题",
            "keyflux_enable_custom_theme_title" to "启用自定义配色",
            "keyflux_enable_custom_theme_summary" to "为键盘背景、按键、文字和强调色使用自定义调色板",
            "keyflux_theme_editor_title" to "编辑调色板",
            "keyflux_theme_editor_summary" to "浅色背景 %s，深色背景 %s",
            "keyflux_theme_editor_dialog_title" to "KeyFlux 调色板",
            "keyflux_theme_mode_light" to "浅色",
            "keyflux_theme_mode_dark" to "深色",
            "keyflux_theme_preset" to "预设",
            "keyflux_theme_preset_choose" to "选择预设",
            "keyflux_theme_preset_amoled" to "AMOLED",
            "keyflux_theme_preset_ocean" to "海洋",
            "keyflux_theme_preset_sakura" to "樱花",
            "keyflux_theme_reset" to "恢复当前默认",
            "keyflux_theme_export" to "复制配置",
            "keyflux_theme_import" to "导入配置",
            "keyflux_theme_import_title" to "粘贴 KeyFlux 配置",
            "keyflux_theme_import_invalid" to "配置格式无效",
            "keyflux_theme_exported" to "主题配置已复制",
            "keyflux_theme_save_failed" to "主题配置保存失败",
            "keyflux_theme_role_background" to "键盘背景",
            "keyflux_theme_role_key_surface" to "按键底色",
            "keyflux_theme_role_key_pressed" to "按键按下",
            "keyflux_theme_role_primary" to "文字与图标",
            "keyflux_theme_role_secondary" to "次要文字",
            "keyflux_theme_role_accent" to "强调与操作",
            "keyflux_theme_hue" to "色相",
            "keyflux_theme_saturation" to "饱和度",
            "keyflux_theme_value" to "明度",
            "keyflux_theme_alpha" to "透明度",
            "keyflux_panel_colors" to "颜色",
            "keyflux_panel_actions" to "操作",
            "keyflux_panel_value" to "数值",
            "keyflux_metered_downloads_title" to "移动网络下载",
            "keyflux_metered_downloads_summary" to "允许通过移动数据下载语言和语音包",
            "keyflux_force_incognito_title" to "强制无痕模式",
            "keyflux_force_incognito_summary" to "要求 Gboard 不进行个性化学习",
            "keyflux_enable_privacy_title" to "阻止遥测和分析",
            "keyflux_enable_privacy_summary" to "停用输入统计、速度日志和本地训练更新",
            "keyflux_secure_clipboard_title" to "剪贴板保护",
            "keyflux_secure_clipboard_summary" to "不保存密码和一次性验证码等敏感内容",
            "keyflux_clip_size_title" to "剪贴板历史数量",
            "keyflux_clip_size_summary" to "当前：%s",
            "keyflux_clip_days_title" to "剪贴板保留时间",
            "keyflux_clip_days_summary" to "输入 0 表示永久保留（当前：%s）",
            "keyflux_log_switch_title" to "调试日志",
            "keyflux_log_switch_summary" to "将诊断信息写入 Xposed 日志",
            "keyflux_force_stop_title" to "应用更改",
            "keyflux_force_stop_summary" to "打开 Gboard 应用信息以强制停止并重新启动",
            "forever" to "永久",
            "days" to "天",
            "keyflux_settings_header_experimental_title" to "AI 和实验功能",
            "keyflux_enable_inline_suggestions_title" to "内联多词建议",
            "keyflux_enable_inline_suggestions_summary" to "在输入位置显示整句或多词预测",
            "keyflux_enable_proactive_emoji_title" to "主动表情工坊",
            "keyflux_enable_proactive_emoji_summary" to "输入时显示动态表情组合建议",
            "keyflux_enable_clipboard_chips_title" to "剪贴板操作按钮",
            "keyflux_enable_clipboard_chips_summary" to "为复制内容显示快速操作和数据提取按钮",
            "keyflux_enable_tflite_engine_title" to "TFLite 预测引擎",
            "keyflux_enable_tflite_engine_summary" to "使用设备端模型进行下一个词和表情预测",
            "keyflux_enable_fast_access_title" to "新版快速访问栏",
            "keyflux_enable_fast_access_summary" to "启用新版快速工具栏和 Google Sans 样式",
            "keyflux_warning_failed_hooks_title" to "兼容性提示：部分功能已停用",
            "keyflux_warning_failed_hooks_summary" to "失败的 Hook：%s",
            "keyflux_feature_unavailable_clipboard" to "当前 Gboard 版本不支持剪贴板增强。",
            "keyflux_feature_unavailable_flags" to "当前 Gboard 版本不支持实验功能开关。",
            "keyflux_feature_unavailable_theme" to "当前 Gboard 版本不支持主题增强。"
        ),
        "en" to mapOf(
            "keyflux_log_level_title" to "Log level",
            "keyflux_log_level_summary" to "Record module logs at %s and above",
            "keyflux_log_level_debug" to "Debug",
            "keyflux_log_level_info" to "Info",
            "keyflux_log_level_warn" to "Warning",
            "keyflux_log_level_error" to "Error",
            "keyflux_category_title" to "KeyFlux Settings",
            "keyflux_enable_ai_title" to "Smart Typing Features",
            "keyflux_enable_ai_summary" to "Enable Smart Compose, inline suggestions, etc.",
            "keyflux_enable_grammar_title" to "Grammar Checker",
            "keyflux_enable_grammar_summary" to "Highlight and correct grammatical errors",
            "keyflux_enable_chinese_learning_title" to "Enhanced Chinese Personalization",
            "keyflux_enable_chinese_learning_summary" to "Keep local Chinese training data and preserve learned word frequency",
            "keyflux_enable_multilingual_title" to "Multilingual Typing",
            "keyflux_enable_multilingual_summary" to "Type in multiple languages simultaneously",
            "keyflux_enable_floating_title" to "Floating Keyboard Layout",
            "keyflux_enable_floating_summary" to "Auto-float keyboard in landscape or multi-window mode",
            "keyflux_enable_emoji_kitchen_title" to "Emoji Kitchen",
            "keyflux_enable_emoji_kitchen_summary" to "Browse and combine stickers and emojis",
            "keyflux_enable_access_point_title" to "Redesign Access Point Menu",
            "keyflux_enable_access_point_summary" to "Silk theme, system font, custom themes",
            "keyflux_enable_amoled_title" to "AMOLED Black Theme",
            "keyflux_enable_amoled_summary" to "Pure black background theme",
            "keyflux_theme_category_title" to "Custom Theme",
            "keyflux_enable_custom_theme_title" to "Enable Custom Colors",
            "keyflux_enable_custom_theme_summary" to "Use your own palette for the keyboard, keys, text, and accents",
            "keyflux_theme_editor_title" to "Edit Palette",
            "keyflux_theme_editor_summary" to "Light background %s, dark background %s",
            "keyflux_theme_editor_dialog_title" to "KeyFlux Palette",
            "keyflux_theme_mode_light" to "Light",
            "keyflux_theme_mode_dark" to "Dark",
            "keyflux_theme_preset" to "Preset",
            "keyflux_theme_preset_choose" to "Choose preset",
            "keyflux_theme_preset_amoled" to "AMOLED",
            "keyflux_theme_preset_ocean" to "Ocean",
            "keyflux_theme_preset_sakura" to "Sakura",
            "keyflux_theme_reset" to "Reset current",
            "keyflux_theme_export" to "Copy config",
            "keyflux_theme_import" to "Import config",
            "keyflux_theme_import_title" to "Paste KeyFlux config",
            "keyflux_theme_import_invalid" to "Invalid theme config",
            "keyflux_theme_exported" to "Theme config copied",
            "keyflux_theme_save_failed" to "Failed to save theme config",
            "keyflux_theme_role_background" to "Keyboard background",
            "keyflux_theme_role_key_surface" to "Key surface",
            "keyflux_theme_role_key_pressed" to "Pressed key",
            "keyflux_theme_role_primary" to "Text and icons",
            "keyflux_theme_role_secondary" to "Secondary text",
            "keyflux_theme_role_accent" to "Accent and actions",
            "keyflux_theme_hue" to "Hue",
            "keyflux_theme_saturation" to "Saturation",
            "keyflux_theme_value" to "Value",
            "keyflux_theme_alpha" to "Alpha",
            "keyflux_panel_colors" to "Colors",
            "keyflux_panel_actions" to "Actions",
            "keyflux_panel_value" to "Value",
            "keyflux_metered_downloads_title" to "Metered Network Downloads",
            "keyflux_metered_downloads_summary" to "Allow language & speech pack downloads over mobile data",
            "keyflux_force_incognito_title" to "Force Incognito Mode",
            "keyflux_force_incognito_summary" to "Force Gboard into incognito mode to prevent saving typing history",
            "keyflux_enable_privacy_title" to "Block Telemetry & Analytics",
            "keyflux_enable_privacy_summary" to "Disable typing statistics, speed logs, and local training updates",
            "keyflux_secure_clipboard_title" to "Clipboard Protection",
            "keyflux_secure_clipboard_summary" to "Prevent saving passwords and one-time passwords (OTP) in clipboard history",
            "keyflux_clip_size_title" to "Clipboard History Size",
            "keyflux_clip_size_summary" to "Current: %s",
            "keyflux_clip_days_title" to "Clipboard Expire Time",
            "keyflux_clip_days_summary" to "Days to keep clipboard items. Enter 0 for forever (Current: %s)",
            "keyflux_log_switch_title" to "Log Switch",
            "keyflux_log_switch_summary" to "Write debug logs to Xposed",
            "keyflux_force_stop_title" to "Apply Changes (Force Stop)",
            "keyflux_force_stop_summary" to "Restart Gboard to apply settings",
            "forever" to "Forever",
            "days" to "days",
            "keyflux_settings_header_experimental_title" to "AI & Experimental Features",
            "keyflux_enable_inline_suggestions_title" to "Inline Multiword Suggestions",
            "keyflux_enable_inline_suggestions_summary" to "Smart Compose-like suggestions for entire sentences inline",
            "keyflux_enable_proactive_emoji_title" to "Proactive Emoji Kitchen",
            "keyflux_enable_proactive_emoji_summary" to "Interactive and animated emoji mashup suggestions while typing",
            "keyflux_enable_clipboard_chips_title" to "Clipboard Action Chips",
            "keyflux_enable_clipboard_chips_summary" to "Smart action buttons for quick paste and data extraction on copy",
            "keyflux_enable_tflite_engine_title" to "TFLite AI Engine",
            "keyflux_enable_tflite_engine_summary" to "Run local neural network for highly accurate next-word and emoji prediction",
            "keyflux_enable_fast_access_title" to "New Fast Access Bar",
            "keyflux_enable_fast_access_summary" to "Enable the new fast access toolbar and Google Sans redesign",
            "keyflux_warning_failed_hooks_title" to "Compatibility Alert: Some Features Disabled",
            "keyflux_warning_failed_hooks_summary" to "Failed hooks: %s. This Gboard version might be incompatible. Please update KeyFlux.",
            "keyflux_feature_unavailable_clipboard" to "Unavailable: Clipboard hook incompatibility.",
            "keyflux_feature_unavailable_flags" to "Unavailable: System flags hook incompatibility.",
            "keyflux_feature_unavailable_theme" to "Unavailable: Theme hook incompatibility."
        )
    )

    fun getString(key: String): String {
        val lang = Locale.getDefault().language
        val map = translations[lang] ?: translations["en"]!!
        val cleanKey = if (key.startsWith("keyflux_")) key else "keyflux_$key"
        val fallbackKey = if (key.startsWith("keyflux_")) key.removePrefix("keyflux_") else key
        return map[cleanKey] ?: map[fallbackKey] ?: translations["en"]!![cleanKey] ?: translations["en"]!![fallbackKey] ?: key
    }
}
